### ISSUE TITLE
Code review: variable construction

### ISSUE THREAD

**Issue by sebxwolf** [worldbank/covid-mobile-data#30]
# Variable construction code review checklist

**to be tested on sample dataset in docker environment**

**21.5.2020**  

Note: Additions to documentation and commenting would be great, if you can think of sth as you go through the code, please add, commit and make a PR!

## List of files to be checked
`notebooks/modules/custom_aggregations.py` and (if time allows) `notebooks/modules/scaled_aggregations.py`

Focus on: *Priority Indicators* as indicated in the script

## List of auxiliary documents
- Documentation
- Word document on priority indicators, slack channel *computation*

## Reproducibility
- [ ] All scripts run from the master after adding the data to the correct folder
- [x] The master script is organized in a way that allows you to understand the general tasks being performed in the code
- [ ] The master script tracks which scripts create and use which files

## Code organization and readability
- [x] Code names are informative 
- [x] It is clear in the code why tasks are being executed
- [x] The code structure facilitates understanding of the tasks
- [x] Code uses white space to improve readability
- [ ] There is extensive use of comments to explain the code
- [x] The code is efficient (tasks are executed in the simplest way possible, loops are used when needed rather than repeating lines, pre-defined functions are used)
- [x] Common tasks are abstracted and automated (e.g. using functions or macros)

## Construction scripts
- [ ] Do you understand how and why each variable is constructed? If not, indicate to the author where more comments are needed.
- [ ] Check merges. Are any observations dropped? If so, is there a clear justification for that? If any observations didn't match, is that explained in the comments?
- [ ] Check collapses. How are missing values treated?
- [ ] Check treatment of missing values. Are research decisions well documented? Are there cases where you think missing values are being created or replaced unintentionally?
- [ ] Check creation of new variables. Does the code match the variable definition in the documentation? Is the correct function being used?
- [ ] Is there always clear documentation of why observations are dropped, if any?

## Constructed dataset(s)
- [ ] Is the resulting data set tidy (each row is an observation, each column is a variable)?
- [ ] Are variable names informative?
- [ ] Are variable labels informative?
- [ ] Is there clear documentation (variable dictionary, variable labels, notes, comments) about variable definition?
- [ ] Are data set names informative?

**Comment by LeonardoViotti** [comment]
-  Rename [agregation_offsite.ipynb](https://github.com/worldbank/covid-mobile-data/blob/master/cdr-aggregation/notebooks/agregation_offsite.ipynb) or change documentation to make it obvious that it is the master script.

**Comment by sebxwolf** [comment]
Thanks @LeonardoViotti, that definitely wasn't clear. I added a reference in the cdr-aggregation readme, but we should probably rename the notebook. Maybe just call it `aggregation`?

**Comment by LeonardoViotti** [comment]
> Thanks @LeonardoViotti, that definitely wasn't clear. I added a reference in the cdr-aggregation readme, but we should probably rename the notebook. Maybe just call it `aggregation`?

My understanding is that the main purpose of all the code inside cdr-aggregation folder is to output the aggregated files. Since that is the file that does it, I would call it something that makes it immediately obvious for someone not familiar that this is the code the does this,  MASTER_aggregation or something similar.

**Comment by LeonardoViotti** [comment]
Comments or suggestions:

- I think it would be nice to document the code more thoroughly. For example, looking at custom_aggregations, it is hard to understand at first glance how indicator [5](https://github.com/worldbank/covid-mobile-data/blob/82791a205bb863ec5efade695ef84dfad5bcc804/cdr-aggregation/notebooks/modules/custom_aggregations.py#L268) is different from other similar methods, e.g. [here](https://github.com/worldbank/covid-mobile-data/blob/82791a205bb863ec5efade695ef84dfad5bcc804/cdr-aggregation/notebooks/modules/custom_aggregations.py#L427).

- I would also document document in the master (or in external documentation) what each file does. There is a lot of abstraction in this code and it would be particularly useful for someone trying to replicate this to know where each class is defined and what it does. The ideal scenario, there would be a mapping of all files in the master mentioning what they do.

 - Add optional saving attribute so you can run the code without creating outputs. This is mostly for testing the code without overwriting existing files.
- Probably a good idea to define constants, e.g. number of obs we are setting as the minimum not to be considered missing, as class variables or attributes so they can be easily modified. I did it for scaled_aggregations.py in a3c17b02475b5a78c568465d5690ecca211b0ea0,  and for custom_aggregations.py in 076192fff37dcb6610165331c4399eb4c7fb4973 but not sure if that's the  best way to do it and I assume the same situation might be happening elsewhere.
- There is a lot of commented out code, which makes it harder to read the code. I imagine a lot of these were slightly different versions of indicators. Particularly with github, there is not a lot of reason to keep that in the code. I did that for custom_aggregations in 82791a205bb863ec5efade695ef84dfad5bcc804.

**Comment by sebxwolf** [comment]
I acted on points 2,4 and 5 in my latest pull request. Point 1 and 3 need a bit more work.
